# Generated by Django 3.0.7 on 2020-06-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='long_url',
            field=models.URLField(unique=True, verbose_name=''),
        ),
    ]
