# Generated by Django 3.0.7 on 2020-06-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200606_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='long_url',
            field=models.URLField(verbose_name=''),
        ),
    ]
