# Generated by Django 3.0.7 on 2020-06-06 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200606_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_urls',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
